export const SIGHT_CHARTS = 'SIGHT_CHARTS';
export const SIGHT_ACTIVE = 'SIGHT_ACTIVE';
export const SIGHT_INACTIVE = 'SIGHT_INACTIVE';
export const SIGHT_LIKE = 'SIGHT_LIKE';
export const SIGHT_UPDATE_CATEGORY = 'SIGHT_UPDATE_CATEGORY';
export const SIGHT_UPDATE_DESCRIPTION = 'SIGHT_UPDATE_DESCRIPTION';
export const SIGHT_UPDATE_NAME = 'SIGHT_UPDATE_NAME';
